apiVersion: v1
kind: Service
metadata:
  name: customer-api
  namespace: customer-ssr
spec:
  type: NodePort
  selector:
    app: customer-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30600
