apiVersion: v1
kind: Service
metadata:
  name: web-ssr
  namespace: customer-ssr
spec:
  type: NodePort
  selector:
    app: web-ssr
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
